# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\nhelloworld\"\xbc\x01\n\x07\x45xample\x12\n\n\x02id\x18\x01 \x02(\x05\x12\t\n\x01i\x18\x02 \x01(\x05\x12\t\n\x01\x64\x18\x03 \x01(\x01\x12\x0f\n\x01\x62\x18\x04 \x01(\x08:\x04true\x12%\n\x01r\x18\x05 \x03(\x0b\x32\x1a.helloworld.Example.Nested\x1a:\n\x06Nested\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x01\x65\x18\x02 \x01(\x0e\x32\x15.helloworld.Example.E:\x02\x45\x31\"\x1b\n\x01\x45\x12\x06\n\x02\x45\x31\x10\x00\x12\x06\n\x02\x45\x32\x10\x01\x12\x06\n\x02\x45\x33\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXAMPLE._serialized_start=30
  _EXAMPLE._serialized_end=218
  _EXAMPLE_NESTED._serialized_start=131
  _EXAMPLE_NESTED._serialized_end=189
  _EXAMPLE_E._serialized_start=191
  _EXAMPLE_E._serialized_end=218
# @@protoc_insertion_point(module_scope)
